apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-html
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simple-html
  template:
    metadata:
      labels:
        app: simple-html
    spec:
      containers:
        - name: simple-html
          image: local/simple-html:v1
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: simple-html
spec:
  selector:
    app: simple-html
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: NodePort
