name: CI
on:
  - pull_request
jobs:
  job1:
    runs-on: ubuntu-latest
    name: Build example and deploy to minikube
    steps:
    - uses: actions/checkout@v4
    - name: Start minikube
      uses: medyagh/setup-minikube@latest
    - name: Build image
      run: |
        minikube image build -t local/simple-html:v1 .
    - name: Deploy to minikube
      run: |
        kubectl apply -f deploy/k8s.yaml
        kubectl wait --for=condition=ready pod -l app=simple-html
    - name: Test service URLs
      run: |
        minikube service list
        minikube service simple-html --url
        curl $(minikube service simple-html --url)
