name: Minikube CI Test

on:
  pull_request:

jobs:
  test-on-minikube:
    runs-on: ubuntu-latest
    name: Build and Deploy to Minikube
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Start Minikube
        uses: medyagh/setup-minikube@latest

      - name: Verify cluster
        run: kubectl get nodes

      - name: Build image using Minikube
        run: |
          minikube image build -t local/example:latest .

      - name: Deploy to Minikube
        run: |
          kubectl apply -f deploy/k8s.yaml
          kubectl wait --for=condition=ready pod -l app=example --timeout=120s

      - name: Test service
        run: |
          minikube service list
          URL=$(minikube service example --url)
          echo "Service URL: $URL"
          curl $URL || echo "Service test failed"
