name: CI

on:
  pull_request:
    branches:
      - main  # Trigger workflow for pull requests to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Minikube
      uses: medyagh/setup-minikube@latest
      with:
        minikube-version: 'latest'

    - name: Start Minikube
      run: minikube start

    - name: Build Docker image using Minikube
      run: minikube image build -t local/devex:v1 .

    - name: Deploy to Minikube
      run: |
        kubectl apply -f deploy/k8s.yaml
        kubectl wait --for=condition=ready pod -l app=simple-html

    - name: Get Service URL
      run: |
        echo "Access your service at:"
        minikube service simple-html --url
